dist.ini
lib/Bio/Roary/External/Mcl.pm
lib/Bio/Roary/PostAnalysis.pm
lib/Bio/Roary/SplitGroups.pm
t/Bio/Roary/CommandLine/Roary.t
t/Bio/Roary/External/Mcl.t

Delete intermediate FAA files by default
Split groups uses File::Temp module for temp files 
Close open file handles to  get rid of warning message when cleaning up temp dir.

Cleanup files

---

lib/Bio/Roary/AnnotateGroups.pm

Perl versions prior to 5.14 raise a compilation error
when an hash has not been de-referenced
Should fix issue #128

Backward compatible deferencing of hashes

---

.travis.yml

...not the patch
It seems odd but Travis gets confused and their perlbrew installs stuff into the wrong place which then means that `dzil test` fails.  Anyway, my fault because their docs say not to provide such a specific version.

TravisCI only wants the major and minor version of perl

---

dist.ini
lib/Bio/Roary/CommandLine/RoaryPostAnalysis.pm
t/Bio/Roary/CommandLine/Roary.t

Ram requirement is too high for generating core trees straight off with fasttree, removed.

revert core tree generation

---

README.md
dist.ini
lib/Bio/Roary/CommandLine/CreatePanGenome.pm
lib/Bio/Roary/CommandLine/Roary.pm
lib/Bio/Roary/External/CheckTools.pm
lib/Bio/Roary/External/IterativeCdhit.pm
t/00_requires_external.t
t/Bio/Roary/CommandLine/Roary.t
t/Bio/Roary/External/CheckTools.t

Addresses the following issues:
https://github.com/sanger-pathogens/Roary/issues/175
https://github.com/sanger-pathogens/Roary/issues/168
https://github.com/sanger-pathogens/Roary/issues/171
New option to report on dependancies to make debugging easier.
Check for at least 2 input files.
Make mafft a required executable

Check dependancies

---

README.md
dist.ini

Fixes issues raised in:
https://github.com/sanger-pathogens/Roary/issues/196
RT499877
RT496629

add optional dependancy from File::Slurper to stop warnings being printed

---

dist.ini
lib/Bio/Roary/AccessoryBinaryFasta.pm
t/Bio/Roary/AccessoryBinaryFasta.t
t/Bio/Roary/CommandLine/Roary.t

Fixes issue:
https://github.com/sanger-pathogens/Roary/issues/202
where the accessory fasta file is full of C's and the tree has no branch lengths

Accessory binary fasta contains all C's fix

---

bin/create_pan_genome_plots.R
contrib/roary_plots/roary_plots.py
dist.ini
lib/Bio/Roary/External/Cdhit.pm
lib/Bio/Roary/External/IterativeCdhit.pm
t/Bio/Roary/External/Cdhit.t

Its been reported that CD-hit crashes when its given more than ~50 threads. This PR introduces a hard limit of 40 to be on the safe side.
Also labels in the roary_plots.py & R scripts have been made consistent with the other figures.

CD-hit threads limit

---

dist.ini
lib/Bio/Roary/AssemblyStatistics.pm
t/Bio/Roary/AssemblyStatistics.t

If the core definition contained decimal places, the summary statistics file rounded down to the nearest integer for the core gene count.

Core gene count

---

contrib/roary_plots/roary.html
contrib/roary_plots/roary_plots.ipynb
contrib/roary_plots/roary_plots.py

The latest genes_presence_absence.csv format "breaks" the contributed script, because of the additional information columns.
This fix restores the functionality of the scripts.

roary_plots: new fields in roary output must be parsed away

---

dist.ini
install_dependencies.sh
lib/Bio/Roary/AccessoryBinaryFasta.pm
t/Bio/Roary/AccessoryBinaryFasta.t

This PR fixes issue https://github.com/sanger-pathogens/Roary/issues/225 
All accessory genes are now made available for building the binary tree

Provide full accessory for building binary tree

---

lib/Bio/Roary/ParallelAllAgainstAllBlast.pm

Hi Andrew,
I got the following error while running roary:
Can't exec "/bin/sh": Argument list too long at /tools/roary/lib/Bio/Roary/ParallelAllAgainstAllBlast.pm line 92, <GEN54> line 647671.
awk: fatal: cannot open file `_blast_results' for reading (No such file or directory)
Looking at that line (the bold one in the sub below):
sub _combine_blast_results {
my ( $self, $output_files ) = @_;
for my $output_file ( @{$output_files} ) {
Bio::Roary::Exceptions::FileNotFound->throw( error => "Cant find blast results: " . $output_file )
unless ( -e $output_file );
}
my $output_files_param = join( ' ', @{$output_files} );
system( "cat $output_files_param > " . $self->blast_results_file_name );                                                                       
return 1;
}
The error comes …

fix bug Can't exec /bin/sh: Argument list too long

---

lib/Bio/Roary/CommandLine/Common.pm

On newer log4perl versions, current use of `easy_init()` leads to a
warning message being printed at runtime ("All arguments to easy_init
should be either an integer log level or a hash reference").
This patch changes this call to use the preferred syntax.

get rid of warning message

---

README.md
dist.ini
lib/Bio/Roary/External/Makeblastdb.pm
t/Bio/Roary/External/Makeblastdb.t
t/bin/dummy_makeblastdb
t/bin/dummy_segmasker

From blast+ 2.5.0 the functionality of parse_seqids changed when building databases (makeblastdb). This updated removes the flag.

Support latest version of blast

---

dist.ini
lib/Bio/Roary.pm
lib/Bio/Roary/CommandLine/Roary.pm
lib/Bio/Roary/CommandLine/RoaryCoreAlignment.pm
lib/Bio/Roary/CommandLine/RoaryPostAnalysis.pm
lib/Bio/Roary/External/GeneAlignmentFromNucleotides.pm
lib/Bio/Roary/External/PostAnalysis.pm
lib/Bio/Roary/ExtractCoreGenesFromSpreadsheet.pm
lib/Bio/Roary/MergeMultifastaAlignments.pm
t/Bio/Roary/ExtractCoreGenesFromSpreadsheet.t

If a gene is a paralog and its core, then allow it in the core gene alignment when the --allow_paralogs option is selected.  The gene names are sorted lexographically and the first is chosen for the core gene alignment if there is a paralog.

Optionally allow paralogs in core gene alignment

---

lib/Bio/Roary/CommandLine/Roary.pm

I am not a Perl guy, but hopefully this is helpful!  It uses the filename library to check through the positional gff args and throws a error if it sees duplicate basenames that would otherwise cause issues downstream.

Issue #363 add check for duplicate basenames

---

README.md
dist.ini
lib/Bio/Roary/CommandLine/Roary.pm

When passing in '-a' with no files, it exits gracefully. If you pass in input files, it performs the dependancy checks and it continues to run as normal.
https://github.com/sanger-pathogens/Roary/issues/269

Fix dependancy checking option

---

contrib/roary_plots/roary_plots.py

Caused by newer versions of matplotlib; this change is backwards compatible

Avoid deprecation errors in roary_plots

---

README.md

I noticed I had to install these too in order for `roary -a` to work...

also mention Devel::OverloadInfo and Digest::MD5::File as required Perl dependencies

---

contrib/roary_plots/roary_plots.py

Since 0.20.1 .loc is the preferred index lookup method instead of .ix
https://pandas.pydata.org/pandas-docs/version/0.20/whatsnew.html#deprecate-ix

Update roary_plots from .ix to .loc

---

lib/Bio/Roary/External/CheckTools.pm

Needed for newer versions of cd-hit

Fix cd-hit version check regexp

---

lib/Bio/Roary/External/CheckTools.pm

The regex searching for the version of `cd-hit` contained an error when compared to the regex for `cdhit`.

Fixed version check for cd-hit

---

contrib/roary_plots/roary_plots.py

Fix the following warning:
```
roary_plots.py:85: FutureWarning: read_table is deprecated, use read_csv instead.
low_memory=False)
```

Fix warning in roary_plots.py

---

contrib/roary_plots/roary_plots.ipynb

newer pandas version use `.loc` rather than `.ix`
see: https://pandas.pydata.org/pandas-docs/version/0.23.4/generated/pandas.DataFrame.ix.html fore more info.
same goes for matplotlib from `axisbg` to `facecolor`

fixed error by old pandas version
